name: Prevent Direct Push to Main

on:
  push:
    branches:
      - main

jobs:
  prevent-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Prevent direct push to main
        run: |
          echo "Direct push to main is not allowed. Raise a PR from the feature branch"
          exit 1